#!/usr/bin/env bash
# Build the WASM front-end **without** starting a server.
# Used by Playwright E2E tests (wasm-server.js will serve the built `www/`).

set -euo pipefail

echo "[build-only] 🔧 building frontend (debug)…" >&2

# --------------------------------------------------
# Prerequisites
# --------------------------------------------------
command -v wasm-pack >/dev/null 2>&1 || {
  echo "[build-only] ❌ wasm-pack not found (install with 'cargo install wasm-pack')." >&2
  exit 1
}

# --------------------------------------------------
# Environment   (allows API_BASE_URL override via repo-root .env)
# --------------------------------------------------
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck source=/dev/null
  . "$ENV_FILE"
  set +a
fi

API_BASE_URL="${API_BASE_URL:-http://localhost:8001}"

# --------------------------------------------------
# Build – dev profile, debuginfo, target web
# --------------------------------------------------
echo "[build-only] 🏗  wasm-pack build …" >&2
API_BASE_URL="$API_BASE_URL" RUSTFLAGS="-C debuginfo=2" \

# Ensure a writable TMPDIR for systems with restricted /var directories (e.g. sandboxed CI)
TMPDIR_OVERRIDDEN="${TMPDIR:-}"
if [[ -z "$TMPDIR_OVERRIDDEN" || ! -w "$TMPDIR_OVERRIDDEN" ]]; then
  export TMPDIR="$(pwd)/.tmp_build"
  mkdir -p "$TMPDIR"
fi

API_BASE_URL="$API_BASE_URL" RUSTFLAGS="-C debuginfo=2" \
  wasm-pack build --dev --target web --out-dir pkg

# Copy the generated files to www directory
echo "[build-only] 📦 copying WASM artifacts to www..." >&2
cp pkg/agent_platform_frontend.js www/
cp pkg/agent_platform_frontend_bg.wasm www/
cp pkg/agent_platform_frontend.d.ts www/
cp pkg/agent_platform_frontend_bg.wasm.d.ts www/

# Ensure output dir exists (wasm-pack creates it but be safe)
mkdir -p www

# --------------------------------------------------
# bootstrap.js – mirrors build-debug.sh minus live server
# --------------------------------------------------
echo "[build-only] ✍️  writing bootstrap.js …" >&2
cat <<'JS' > www/bootstrap.js
import init, { init_api_config_js } from './agent_platform_frontend.js';

async function main() {
  await init();
  const url = window.API_BASE_URL || 'http://localhost:8001';
  init_api_config_js(url);
}

main();
JS

# --------------------------------------------------
# config.js – tiny placeholder so <script src="config.js"> doesn’t 404
# --------------------------------------------------
echo "[build-only] ✍️  writing config.js …" >&2
cat <<'EOF' > www/config.js
// Auto-generated by frontend/build-only.sh
window.__APP_CONFIG__ = window.__APP_CONFIG__ || {};
window.__APP_CONFIG__.BUILD = 'debug';
EOF

echo "[build-only] ✅ build complete (output in frontend/www/)" >&2
