# Swarm Platform Development - Single command to start everything
# Usage: docker compose up

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: zerg
      POSTGRES_USER: zerg
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zerg -d zerg"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
    driver: local
