# uv configuration for this repository.
#
# We force uv's cache directory to be inside the repository so that test runs
# remain hermetic and we avoid permission issues with read-only HOME
# directories on certain CI runners.  Putting the cache inside the repo also
# avoids problems caused by stale or malformed files that can end up in the
# default `~/.cache/uv` location (e.g. a file named `.git` where uv expects a
# directory).

cache-dir = "./.uv_cache"
