# Backend-specific ruff configuration
line-length = 120

[lint]
# Ignore module level imports not at top of file for test files
# This is needed because some test files have docstrings before imports
select = ["I", "E", "F", "Q000"]

[lint.per-file-ignores]
"tests/**/*.py" = ["E402", "E501"]

[lint.isort]
force-single-line = true 