name: API Contract Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  contract-validation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    - name: Start backend server
      run: |
        cd backend
        python -m uvicorn zerg.main:app --host 0.0.0.0 --port 8001 &
        sleep 5
    
    - name: Run contract validation tests
      run: |
        chmod +x scripts/test-phase1-contracts.sh
        ./scripts/test-phase1-contracts.sh
    
    - name: Validate OpenAPI schema contains required fields
      run: |
        if ! grep -q '"from_node_id"' openapi.json; then
          echo "❌ Contract violation: from_node_id field missing from OpenAPI schema"
          exit 1
        fi
        if ! grep -q '"to_node_id"' openapi.json; then
          echo "❌ Contract violation: to_node_id field missing from OpenAPI schema"
          exit 1
        fi
        echo "✅ OpenAPI schema contains required contract fields"